import { canRecordDailyAction } from "./attendance-policy";
import { readJsonState, mutateJsonState, allocate, timestamp, type JsonEmployee, type JsonAttendance, type JsonLocation, type JsonUser } from "./json-store";

export type Employee = JsonEmployee & { createdAt: Date; updatedAt: Date };
export type Attendance = JsonAttendance & { recordedAt: Date };
export type Location = JsonLocation;
export type User = import("../drizzle/schema").User;
export type InsertUser = { openId: string; [key: string]: any };

export async function getDb() { return readJsonState(); }
const dt = (value: string | Date) => value instanceof Date ? value.toISOString() : value;
export async function upsertUser(user: InsertUser) { await mutateJsonState(state => { const existing = state.users.find(row => row.openId === user.openId); const value = { name: user.name ?? null, email: user.email ?? null, branch: user.branch ?? null, latitude: user.latitude ?? null, longitude: user.longitude ?? null, radiusMeters: user.radiusMeters ?? null, loginMethod: user.loginMethod ?? null, role: user.role ?? "user", lastSignedIn: dt(user.lastSignedIn ?? new Date()) } as const; if (existing) Object.assign(existing, value, { updatedAt: timestamp() }); else state.users.push({ id: allocate(state, "user"), openId: user.openId, createdAt: timestamp(), updatedAt: timestamp(), ...value }); }); }
export async function getUserByOpenId(openId: string): Promise<any> { return (await readJsonState()).users.find(row => row.openId === openId) as any; }
export async function getDashboardCredentials() { return (await readJsonState()).credentials ?? undefined; }
export async function saveDashboardCredentials(username: string, passwordHash: string) { await mutateJsonState(state => { state.credentials = { id: 1, username, passwordHash, updatedAt: timestamp() }; }); return getDashboardCredentials(); }
export async function listUsers() { return (await readJsonState()).users.slice().sort((a, b) => (a.name ?? "").localeCompare(b.name ?? "")); }
export async function updateUserAccount(id: number, values: Partial<Pick<JsonUser, "name" | "role" | "branch" | "latitude" | "longitude" | "radiusMeters">>) { await mutateJsonState(state => { const row = state.users.find(item => item.id === id); if (row) Object.assign(row, values, { updatedAt: timestamp() }); }); }
export async function deleteUserAccount(id: number) { await mutateJsonState(state => { state.users = state.users.filter(row => row.id !== id); }); }
export async function listEmployees() { return (await readJsonState()).employees.slice().sort((a, b) => a.branch.localeCompare(b.branch) || a.name.localeCompare(b.name)); }
export async function getEmployee(employeeId: number) { return (await readJsonState()).employees.find(row => row.id === employeeId); }
export async function createEmployee(values: Partial<JsonEmployee> & { name: string; branch: string }) { return mutateJsonState(state => { const employee: JsonEmployee = { id: allocate(state, "employee"), name: values.name, branch: values.branch, latitude: values.latitude ?? null, longitude: values.longitude ?? null, radiusMeters: values.radiusMeters ?? null, phone: values.phone ?? null, telegramChatId: null, telegramPendingAction: null, telegramLinkCodeHash: null, telegramLinkCodeExpiresAt: null, scheduleJson: values.scheduleJson ?? null, defaultStartTime: values.defaultStartTime ?? null, defaultEndTime: values.defaultEndTime ?? null, lastLateAlertDate: null, lastAbsenceAlertDate: null, active: values.active ?? 1, createdAt: timestamp(), updatedAt: timestamp() }; state.employees.push(employee); return employee; }); }
export async function updateEmployee(employeeId: number, values: Partial<Pick<JsonEmployee, "name" | "branch" | "latitude" | "longitude" | "radiusMeters" | "phone" | "active" | "scheduleJson" | "defaultStartTime" | "defaultEndTime">>) { await mutateJsonState(state => { const row = state.employees.find(item => item.id === employeeId); if (row) Object.assign(row, values, { updatedAt: timestamp() }); }); }
export async function deleteEmployee(employeeId: number) { await mutateJsonState(state => { const row = state.employees.find(item => item.id === employeeId); if (row) Object.assign(row, { active: 0, telegramChatId: null, telegramPendingAction: null, telegramLinkCodeHash: null, telegramLinkCodeExpiresAt: null, updatedAt: timestamp() }); }); }
export async function resetEmployeeTelegram(employeeId: number) { await updateEmployeeTelegram(employeeId, { telegramChatId: null, telegramPendingAction: null, telegramLinkCodeHash: null, telegramLinkCodeExpiresAt: null }); }
async function updateEmployeeTelegram(employeeId: number, values: Partial<JsonEmployee>) { await mutateJsonState(state => { const row = state.employees.find(item => item.id === employeeId); if (row) Object.assign(row, values, { updatedAt: timestamp() }); }); }
export async function listLocations() { return (await readJsonState()).locations.filter(row => row.active === 1); }
export async function getLocationByName(name: string) { return (await readJsonState()).locations.find(row => row.name === name); }
export async function getEmployeeByTelegramChatId(chatId: string) { return (await readJsonState()).employees.find(row => row.telegramChatId === chatId); }
export async function linkEmployeeToTelegram(employeeId: number, telegramChatId: string) { await mutateJsonState(state => { const current = state.employees.find(row => row.id === employeeId); if (current?.telegramChatId && current.telegramChatId !== telegramChatId) throw new Error("الموظف مرتبط بحساب تيليجرام آخر"); for (const row of state.employees) if (row.telegramChatId === telegramChatId && row.id !== employeeId) Object.assign(row, { telegramChatId: null, telegramPendingAction: null }); if (current) Object.assign(current, { telegramChatId, telegramPendingAction: null, updatedAt: timestamp() }); }); }
export async function setTelegramPendingAction(employeeId: number, action: "check_in" | "check_out") { await updateEmployeeTelegram(employeeId, { telegramPendingAction: action }); }
export async function clearTelegramPendingAction(employeeId: number) { await updateEmployeeTelegram(employeeId, { telegramPendingAction: null }); }
export async function saveTelegramLinkCode(employeeId: number, codeHash: string, expiresAt: Date) { await updateEmployeeTelegram(employeeId, { telegramLinkCodeHash: codeHash, telegramLinkCodeExpiresAt: expiresAt.toISOString() }); }
export async function consumeTelegramLinkCode(codeHash: string) { const row = (await readJsonState()).employees.find(item => item.telegramLinkCodeHash === codeHash); if (!row || !row.telegramLinkCodeExpiresAt || new Date(row.telegramLinkCodeExpiresAt).getTime() <= Date.now()) return undefined; return row; }
export async function clearTelegramLinkCode(employeeId: number) { await updateEmployeeTelegram(employeeId, { telegramLinkCodeHash: null, telegramLinkCodeExpiresAt: null }); }
export async function claimLateAlert(employeeId: number, dateKey: string) { return mutateJsonState(state => { const row = state.employees.find(item => item.id === employeeId); if (!row || row.lastLateAlertDate === dateKey) return false; row.lastLateAlertDate = dateKey; return true; }); }
export async function claimAbsenceAlert(employeeId: number, dateKey: string) { return mutateJsonState(state => { const row = state.employees.find(item => item.id === employeeId); if (!row || row.lastAbsenceAlertDate === dateKey) return false; row.lastAbsenceAlertDate = dateKey; return true; }); }
export async function getNotificationSettings() { return mutateJsonState(state => { if (!state.settings) state.settings = { id: 1, graceMinutes: 20, summaryTime: "04:00", attendanceStartDate: null, summaryCronTaskUid: null, lastSummaryDate: null, createdAt: timestamp(), updatedAt: timestamp() }; return state.settings; }); }
export async function updateNotificationSettings(values: { graceMinutes?: number; summaryTime?: string; attendanceStartDate?: string | null }) { await mutateJsonState(state => { if (!state.settings) state.settings = { id: 1, graceMinutes: 20, summaryTime: "04:00", attendanceStartDate: null, summaryCronTaskUid: null, lastSummaryDate: null, createdAt: timestamp(), updatedAt: timestamp() }; Object.assign(state.settings, values, { updatedAt: timestamp() }); }); return getNotificationSettings(); }
export async function claimDailySummary(dateKey: string) { return mutateJsonState(state => { const settings = state.settings ?? (state.settings = { id: 1, graceMinutes: 20, summaryTime: "04:00", attendanceStartDate: null, summaryCronTaskUid: null, lastSummaryDate: null, createdAt: timestamp(), updatedAt: timestamp() }); if (settings.lastSummaryDate === dateKey) return false; settings.lastSummaryDate = dateKey; return true; }); }
export async function saveDailyReport(dateKey: string, content: string) { return mutateJsonState(state => { let row = state.reports.find(item => item.dateKey === dateKey); if (!row) { row = { id: allocate(state, "report"), dateKey, content, telegramSentAt: null, createdAt: timestamp(), updatedAt: timestamp() }; state.reports.push(row); } else Object.assign(row, { content, updatedAt: timestamp() }); return row; }); }
export async function markDailyReportTelegramSent(dateKey: string) { await mutateJsonState(state => { const row = state.reports.find(item => item.dateKey === dateKey); if (row) row.telegramSentAt = timestamp(); }); }
export async function listRecentAttendance(limit = 20) { const state = await readJsonState(); return state.attendance.slice().sort((a, b) => b.recordedAt.localeCompare(a.recordedAt)).slice(0, limit).map(record => ({ record, employee: state.employees.find(item => item.id === record.employeeId) ?? null })); }
export async function todaySummary() { const state = await readJsonState(); const start = new Date(); const day = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Riyadh" }).format(start); const records = state.attendance.filter(row => new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Riyadh" }).format(new Date(row.recordedAt)) === day); return { employees: state.employees.filter(row => row.active === 1).length, checkIns: records.filter(row => row.action === "check_in").length, checkOuts: records.filter(row => row.action === "check_out").length, present: new Set(records.map(row => row.employeeId)).size }; }
export async function createAttendance(input: Omit<JsonAttendance, "id">) { return mutateJsonState(state => { const row = { ...input, id: allocate(state, "attendance") }; state.attendance.push(row); return row; }); }
function riyadhDayKey(value: string | Date) { return new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Riyadh" }).format(new Date(value)); }
export async function createAttendanceOncePerDay(input: Omit<JsonAttendance, "id">) { return mutateJsonState(state => { const key = riyadhDayKey(input.recordedAt); const exists = state.attendance.some(row => row.employeeId === input.employeeId && row.action === input.action && riyadhDayKey(row.recordedAt) === key); if (!canRecordDailyAction(exists)) return false; state.attendance.push({ ...input, id: allocate(state, "attendance") }); return true; }); }
export async function findAttendance(id: number) { return (await readJsonState()).attendance.find(row => row.id === id); }
export async function updateAttendance(id: number, values: Partial<JsonAttendance>) { await mutateJsonState(state => { const row = state.attendance.find(item => item.id === id); if (row) Object.assign(row, values); }); }
export async function attendanceForRange(start: Date, end: Date) { return (await readJsonState()).attendance.filter(row => new Date(row.recordedAt) >= start && new Date(row.recordedAt) < end).sort((a, b) => a.recordedAt.localeCompare(b.recordedAt)); }
export async function activeEmployees() { return (await readJsonState()).employees.filter(row => row.active === 1).sort((a, b) => a.branch.localeCompare(b.branch) || a.name.localeCompare(b.name)); }
