import { activeEmployees, attendanceForRange, getNotificationSettings } from "./db";
const TIME_ZONE = "Asia/Riyadh";
export const LATE_GRACE_MINUTES = 20;
export const EARLY_CHECK_IN_MINUTES = 10;
type Local = { key: string; year: number; month: number; weekday: number; minutes: number };
export function localDateParts(date: Date): Local { const p = new Intl.DateTimeFormat("en-US", { timeZone: TIME_ZONE, year: "numeric", month: "2-digit", day: "2-digit", weekday: "short", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).formatToParts(date); const get=(t:string)=>p.find(x=>x.type===t)?.value??"0"; const weekday=({Sun:0,Mon:1,Tue:2,Wed:3,Thu:4,Fri:5,Sat:6} as Record<string,number>)[get("weekday")]??0; return { key:`${get("year")}-${get("month")}-${get("day")}`, year:Number(get("year")), month:Number(get("month")), weekday, minutes:Number(get("hour"))*60+Number(get("minute")) }; }
export function lateMinutesFor(startMinutes:number, actualMinutes:number, graceMinutes=LATE_GRACE_MINUTES) { return Math.max(0, actualMinutes-startMinutes-graceMinutes); }
export function parseSchedule(value:string|null) { try { return JSON.parse(value??"{}") as Record<string,number|null>; } catch { return {}; } }
export function currentLateStatus(scheduleJson:string|null, now=new Date(), graceMinutes=LATE_GRACE_MINUTES) { const current=localDateParts(now); const startMinutes=parseSchedule(scheduleJson)[String(current.weekday)]; if(startMinutes==null) return { scheduled:false, lateMinutes:0, dateKey:current.key, startMinutes:null, actualMinutes:current.minutes }; return { scheduled:true, lateMinutes:lateMinutesFor(startMinutes,current.minutes,graceMinutes), dateKey:current.key, startMinutes, actualMinutes:current.minutes }; }
export function checkInWindow(scheduleJson:string|null, now=new Date(), earlyMinutes=EARLY_CHECK_IN_MINUTES) { const current=localDateParts(now); const startMinutes=parseSchedule(scheduleJson)[String(current.weekday)]; if(startMinutes==null) return {scheduled:false,allowed:true,minutesUntilStart:0}; const minutesUntilStart=startMinutes-current.minutes; return {scheduled:true,allowed:minutesUntilStart<=earlyMinutes,minutesUntilStart}; }
function bounds(month:string) { const [y,m]=month.split("-").map(Number); const start=new Date(`${month}-01T00:00:00+03:00`); const end=new Date(m===12?`${y+1}-01-01T00:00:00+03:00`:`${y}-${String(m+1).padStart(2,"0")}-01T00:00:00+03:00`); return {start,end}; }
function days(start:Date,end:Date) { const out:Local[]=[]; for(let t=new Date(start);t<end;t.setUTCDate(t.getUTCDate()+1)) out.push(localDateParts(t)); return out; }
function formatTime(value:Date|string|undefined) { return value ? new Intl.DateTimeFormat("ar-SA",{timeZone:TIME_ZONE,hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).format(new Date(value)) : null; }
export async function monthlyAttendanceReport(month:string) { const b=bounds(month); const settings=await getNotificationSettings(); const start=settings.attendanceStartDate&&settings.attendanceStartDate>`${month}-01`?new Date(`${settings.attendanceStartDate}T00:00:00+03:00`):b.start; const [emps,records]=await Promise.all([activeEmployees(),attendanceForRange(start,b.end)]); const by=new Map<number,typeof records>(); for(const r of records){const a=by.get(r.employeeId)??[];a.push(r);by.set(r.employeeId,a);} const reportDays=days(start,b.end).filter(d=>new Date(`${d.key}T00:00:00+03:00`)<new Date()); const rows=emps.map(e=>{const ed=by.get(e.id)??[];const detail=reportDays.map(d=>{const day=ed.filter(r=>localDateParts(new Date(r.recordedAt)).key===d.key);const ci=day.find(r=>r.action==="check_in");const co=day.find(r=>r.action==="check_out");const scheduled=parseSchedule(e.scheduleJson)[String(d.weekday)]!=null;const late=ci&&scheduled?lateMinutesFor(parseSchedule(e.scheduleJson)[String(d.weekday)]!,localDateParts(new Date(ci.recordedAt)).minutes,settings.graceMinutes):0;return {date:d.key,status:ci?(late>0?"متأخر":"حاضر"):scheduled?"غياب":"إجازة",checkIn:formatTime(ci?.recordedAt),checkOut:formatTime(co?.recordedAt),locationName:ci?.locationName ?? co?.locationName ?? null,note:ci?.note ?? co?.note ?? null,lateMinutes:late};});return {employeeId:e.id,name:e.name,branch:e.branch,scheduledDays:detail.filter(x=>x.status!=="إجازة").length,attendanceDays:detail.filter(x=>x.checkIn).length,absentDays:detail.filter(x=>x.status==="غياب").length,lateDays:detail.filter(x=>x.lateMinutes>0).length,lateMinutes:detail.reduce((s,x)=>s+x.lateMinutes,0),firstCheckIn:formatTime(ed.find(r=>r.action==="check_in")?.recordedAt),details:detail};});return {month,graceMinutes:settings.graceMinutes,evaluatedThrough:localDateParts(new Date()).key,rows,totals:{scheduledDays:rows.reduce((s,r)=>s+r.scheduledDays,0),attendanceDays:rows.reduce((s,r)=>s+r.attendanceDays,0),absentDays:rows.reduce((s,r)=>s+r.absentDays,0),lateDays:rows.reduce((s,r)=>s+r.lateDays,0),lateMinutes:rows.reduce((s,r)=>s+r.lateMinutes,0)}}; }
export async function monthlyAbsenceRecords(month:string) { const report=await monthlyAttendanceReport(month); const employees=await activeEmployees(); return { month, rows: report.rows.flatMap(row=>row.details.filter(d=>d.status==="غياب").map(d=>({employeeId:row.employeeId,name:row.name,branch:row.branch,date:d.date,scheduledStart:parseSchedule(employees.find(e=>e.id===row.employeeId)?.scheduleJson??null)[String(localDateParts(new Date(`${d.date}T00:00:00+03:00`)).weekday)]??0}))) }; }
export async function dailyAttendanceReport(dateKey:string) { const emps=await activeEmployees(); const start=new Date(`${dateKey}T00:00:00+03:00`);const end=new Date(start.getTime()+86400000);const records=await attendanceForRange(start,end);const rows=emps.map(e=>{const ci=records.find(r=>r.employeeId===e.id&&r.action==="check_in");const co=records.find(r=>r.employeeId===e.id&&r.action==="check_out");const status=currentLateStatus(e.scheduleJson,ci?new Date(ci.recordedAt):start);return {employeeId:e.id,name:e.name,branch:e.branch,checkIn:formatTime(ci?.recordedAt),checkOut:formatTime(co?.recordedAt),status:ci?(status.lateMinutes>0?"متأخر":"حاضر"):status.scheduled?"غياب":"إجازة",lateMinutes:ci?status.lateMinutes:0};});return {dateKey,rows,totals:{present:rows.filter(r=>r.status==="حاضر"||r.status==="متأخر").length,absent:rows.filter(r=>r.status==="غياب").length,late:rows.filter(r=>r.status==="متأخر").length,lateMinutes:rows.reduce((s,r)=>s+r.lateMinutes,0)}}; }
